<a href="https://colab.research.google.com/github/MarMastro/pandas_importar_archivos/blob/master/leyendo_consulta_sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Leyendo un banco de datos**

## **Creando un banco de datos local**

In [6]:
import sqlalchemy

In [7]:
from sqlalchemy import create_engine, MetaData, Table, inspect, text

In [10]:
# Usamos un banco de datos que ya viene por default en Colab que es sqlite. Memory quiere decir que lo vamos
# a almacenar en la memoria de Colab.
engine = create_engine('sqlite:///:memory:')

## **Escribiendo en un banco de datos**

In [1]:
import pandas as pd

In [2]:
# Antes de colocar los datos en una tabla SQL hay que ponerlo en una variable CSV.
archivo = 'clientes_banco.csv'

In [4]:
datos = pd.read_csv(archivo)

In [5]:
datos.head()

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12.0,427500.0,1.0,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12.0,427500.0,1.0,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3.0,112500.0,1.0,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8.0,270000.0,0.0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8.0,270000.0,0.0,Casa/Departamento propio

In [11]:
# Exportamos el archivo en formato sql.
# En el segundo parametro se le debe poner el motor de busqueda.
datos.to_sql('clientes', engine, index = False)

127918

In [12]:
# Con inspect verificamos que creo la tabla dentro del engine.
inspector = inspect(engine)

In [13]:
# Voy a ver las tablas en pantalla. Para eso uso el metodo get_table_names.
print(inspector.get_table_names())

['clientes']

## **Leyendo una consulta SQL**

In [14]:
# Vamos a tomar de la tabla en la columna Categoria de renta solo los empleados.
# SELECT para hacer una consulta(query).
# * para seleccionar todas las consultas.
# WHERE Categoria de renta. La columna que quiero consultar.
# Selecciono Empleado entre comillas
query = 'SELECT * FROM clientes WHERE categoria_de_renta = "Empleado"'

In [16]:
# Para leer la query debo envolverla en el metodo text.
# Lo debo conectar (con) al motor engine.
empleados = pd.read_sql(sql = text(query), con = engine.connect())

In [17]:
type(empleados)

pandas.core.frame.DataFrame

In [18]:
empleados

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12.0,427500.0,1.0,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12.0,427500.0,1.0,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3.0,112500.0,1.0,Casa/Departamento propio
3,5008815,46,Nivel superior,Casado,2,Empleado,Contabilidad,2.0,270000.0,1.0,Casa/Departamento propio
4,5112956,46,Nivel superior,Casado,2,Empleado,Contabilidad,2.0,270000.0,1.0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
65108,6280699,42,Nivel superior,Casado,4,Empleado,Equipo principal,22.0,112500.0,0.0,Casa/Departamento propio
65109,5585084,36,Nivel intermedio,Casado,3,Empleado,Otro,7.0,135000.0,0.0,Casa/Departamento propio
65110,6634221,36,Nivel intermedio,Casado,3,Empleado,Otro,7.0,135000.0,0.0,Casa/Departamento propio
65111,6634222,36,Nivel intermedio,Casado,3,Empleado,Otro,7.0,135000.0,0.0,Casa/Departamento propio
65112,6634223,36,Nivel intermedio,Casado,3,Empleado,Otro,7.0,135000.0,0.0,Casa/Departamento propio

In [19]:
# Guardamos el df en una tabla sql.
empleados.to_sql('empleados', con = engine.connect(), index = False)

65113

In [20]:
# Leo la tabla completa 'empleados'.
pd.read_sql_table('empleados', con = engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12.0,427500.0,1.0,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12.0,427500.0,1.0,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3.0,112500.0,1.0,Casa/Departamento propio
3,5008815,46,Nivel superior,Casado,2,Empleado,Contabilidad,2.0,270000.0,1.0,Casa/Departamento propio
4,5112956,46,Nivel superior,Casado,2,Empleado,Contabilidad,2.0,270000.0,1.0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
65108,6280699,42,Nivel superior,Casado,4,Empleado,Equipo principal,22.0,112500.0,0.0,Casa/Departamento propio
65109,5585084,36,Nivel intermedio,Casado,3,Empleado,Otro,7.0,135000.0,0.0,Casa/Departamento propio
65110,6634221,36,Nivel intermedio,Casado,3,Empleado,Otro,7.0,135000.0,0.0,Casa/Departamento propio
65111,6634222,36,Nivel intermedio,Casado,3,Empleado,Otro,7.0,135000.0,0.0,Casa/Departamento propio
65112,6634223,36,Nivel intermedio,Casado,3,Empleado,Otro,7.0,135000.0,0.0,Casa/Departamento propio

In [25]:
# Para filtrar solo algunas columnas de la tabla 'empleados'.
pd.read_sql_table('empleados', con = engine.connect(), columns = ['ID_Cliente', 'Grado_estudio', 'Rendimiento_anual'])

       ID_Cliente     Grado_estudio  Rendimiento_anual
0         5008804    Nivel superior           427500.0
1         5008805    Nivel superior           427500.0
2         5008806  Nivel intermedio           112500.0
3         5008815    Nivel superior           270000.0
4         5112956    Nivel superior           270000.0
...           ...               ...                ...
65108     6280699    Nivel superior           112500.0
65109     5585084  Nivel intermedio           135000.0
65110     6634221  Nivel intermedio           135000.0
65111     6634222  Nivel intermedio           135000.0
65112     6634223  Nivel intermedio           135000.0

[65113 rows x 3 columns]